{
 "title": "Performance stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Servers",
    "query": {}
   },
   {
    "name": "Shards",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ticks behind",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.performance.$Shards.ticksbehind, 1, 3)"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(groupByNodes(history.$Servers.performance.$Shards.resultcodes.*, 'sumSeries', 1, 5), 0, 1)"
    }
   ]
  },
  {
   "title": "Time taken",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.performance.$Shards.timetakenms, 1, 3)"
    }
   ]
  }
 ]
}