{
 "title": "MMO Leaderboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server", "query": "mmo, seasonal" }
  ]
 },
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GCL Active season",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  avg(score) AS \" \",\r\n  user AS \"metric\"  \r\nFROM ${Server}_current_leaderboard\r\nWHERE timestamp BETWEEN '${__from:date}' AND '${__to:date}'\r\n  AND type = 'gcl' and rank <= 10000000\r\n  SAMPLE BY $__sampleByInterval \r\nALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Power Active season",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  avg(score) AS \" \",\r\n  user AS \"metric\"  \r\nFROM ${Server}_current_leaderboard\r\nWHERE timestamp BETWEEN '${__from:date}' AND '${__to:date}'\r\n  AND type = 'power' and rank <= 10000000\r\nSAMPLE BY $__sampleByInterval \r\nALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GCL historical seasons (top100 rank data only)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  avg(score) AS \" \",\r\n  user AS \"metric\"  \r\nFROM ${Server}_historical_leaderboard\r\nwhere type='gcl' and rank <= 100\r\nSAMPLE BY $__sampleByInterval \r\nALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Power historical seasons (top100 rank data only)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  avg(score) AS \" \",\r\n  user AS \"metric\"  \r\nFROM ${Server}_historical_leaderboard\r\nwhere type='power' and rank <= 100\r\nSAMPLE BY $__sampleByInterval \r\nALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  }
 ]
}