{
 "title": "Adminutils",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Servers",
    "query": {}
   },
   {
    "name": "Users",
    "query": {}
   },
   { "name": "Team1", "query": "{}" },
   { "name": "Team2", "query": "{}" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gametime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.gametime, 3)"
    }
   ]
  },
  {
   "title": "Total rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.totalrooms, 3)"
    }
   ]
  },
  {
   "title": "Active rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.activerooms, 3)"
    }
   ]
  },
  {
   "title": "Owned rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.ownedrooms, 3)"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.activeusers, 3)"
    }
   ]
  },
  { "title": "Tickspeed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Avg tickspeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "aliasByMetric(history.$Servers.adminutils.ticks.avg)"
    }
   ]
  },
  {
   "title": "Tick stage timing",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(history.$Servers.adminutils.ticks.stages.*)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.users.$Users.cpu, 4)"
    }
   ]
  },
  {
   "title": "CPU bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.users.$Users.cpuavailable, 4)"
    }
   ]
  },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CombinedRCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.users.$Users.combinedrcl, 4)"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.users.$Users.rooms, 4)"
    }
   ]
  },
  {
   "title": "Creeps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.users.$Users.creeps, 4)"
    }
   ]
  },
  { "title": "Leaderboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "GCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.users.*.gcl, 4)"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(history.$Servers.adminutils.users.$Users.power, 4)"
    }
   ]
  },
  {
   "title": "Leaderboard team based",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "GCL teams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(groupByNode(history.$Servers.adminutils.users.$Team1.gcl, 3, 'sum'), 'Team 1', false)"
      },
      {
       "target": "alias(groupByNode(history.$Servers.adminutils.users.$Team2.gcl, 3, 'sum'), 'Team 2', false)"
      }
     ]
    },
    {
     "title": "GCL team 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(history.$Servers.adminutils.users.$Team1.gcl, 4)"
      }
     ]
    },
    {
     "title": "GCL team 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(history.$Servers.adminutils.users.$Team2.gcl, 4)"
      }
     ]
    },
    {
     "title": "GCL teams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(groupByNode(history.$Servers.adminutils.users.$Team1.combinedrcl, 3, 'sum'), 'Team 1', false)"
      },
      {
       "target": "alias(groupByNode(history.$Servers.adminutils.users.$Team2.combinedrcl, 3, 'sum'), 'Team 2', false)"
      }
     ]
    },
    {
     "title": "Combined RCL 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(history.$Servers.adminutils.users.$Team1.combinedrcl, 4)"
      }
     ]
    },
    {
     "title": "CombinedRCL team 2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(history.$Servers.adminutils.users.$Team2.combinedrcl, 4)"
      }
     ]
    }
   ]
  }
 ]
}