// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserTrackerShared.DBClients.TimeScaleDB;

#nullable disable

namespace UserTrackerShared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250614202908_AddedOtherModels")]
    partial class AddedOtherModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserTrackerShared.Models.TimeScaleDB.TimeScaleAdminUtilsDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveRooms")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("integer");

                    b.Property<long>("GameTime")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OwnedRooms")
                        .HasColumnType("integer");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("integer");

                    b.Property<string>("UsersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("AdminUtilsData");
                });

            modelBuilder.Entity("UserTrackerShared.Models.TimeScaleDB.TimeScaleScreepsRoomHistoryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Base")
                        .HasColumnType("bigint");

                    b.Property<string>("CreepsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GroundResourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StructuresJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TimeScaleScreepsRoomHistoryDto");
                });

            modelBuilder.Entity("UserTrackerShared.Models.TimeScaleDB.TimeScaleScreepsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("GCL")
                        .HasColumnType("bigint");

                    b.Property<int>("GCLRank")
                        .HasColumnType("integer");

                    b.Property<long>("Power")
                        .HasColumnType("bigint");

                    b.Property<int>("PowerRank")
                        .HasColumnType("integer");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserTrackerShared.Models.TimeScaleDB.TimeScaleSeasonItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SeasonItems");
                });

            modelBuilder.Entity("UserTrackerShared.Models.TimeScalePerformanceClassDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ResultCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TicksBehind")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("TimeTakenMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PerformanceStats");
                });
#pragma warning restore 612, 618
        }
    }
}
