// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserTrackerShared.DBClients.TimeScaleDB;

#nullable disable

namespace UserTrackerShared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613181713_InitialTimescale")]
    partial class InitialTimescale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserTrackerShared.Models.TimeScaleDB.TimeScaleScreepsRoomHistoryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Base")
                        .HasColumnType("bigint");

                    b.Property<string>("CreepsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GroundResourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StructuresJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScreepsRoomHistory");
                });

            modelBuilder.Entity("UserTrackerShared.Models.TimeScalePerformanceClassDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ResultCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TicksBehind")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("TimeTakenMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PerformanceStats");
                });
#pragma warning restore 612, 618
        }
    }
}
