{
 "title": "Graphite Go-Carbon Metrics",
 "description": "For the metrics of the go-carbon implementation as alternative to the original Python carbon.",
 "tags": [
  "graphite",
  "carbon"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "agent", "label": "Carbon Agent", "query": "stats.gocarbon.agents.*" }
  ]
 },
 "panels": [
  {
   "title": "Metric Inputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.tcp.metricsReceived), 4)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.udp.metricsReceived), 4)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.pickle.metricsReceived), 5)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.*.errors), 4)"
    }
   ]
  },
  {
   "title": "Persister Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.updateOperations), 'Updates')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.committedPoints), 'Committed Points')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.created), 'Creates')"
    },
    {
     "target": "alias(sumSeries(stats.gocarbon.agents.$agent.persister.pointsPerUpdate), 'Points per Update')"
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.size), 5)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.queries), 5)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.maxSize), 5)"
    },
    {
     "target": "aliasByNode(sumSeries(stats.gocarbon.agents.$agent.cache.overflow), 5)"
    }
   ]
  },
  {
   "title": "Queue Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gocarbon.agents.$agent.cache.queueWriteoutTime, 'Queue Writeout Time')"
    },
    {
     "target": "alias(stats.gocarbon.agents.$agent.cache.queueBuildTimeMs, 'Queue Build Time')"
    },
    {
     "target": "alias(stats.gocarbon.agents.$agent.cache.queueBuildCount, 'Queue Rebuilds')"
    }
   ]
  }
 ]
}