{
 "title": "MMO Performance Puller",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Shard",
    "query": "SELECT distinct\n  shard\nFROM td3_performance"
   }
  ]
 },
 "panels": [
  {
   "title": "Ticks behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  avg(ticksBehind) AS \" \",\r\n  shard AS \"metric\"\r\nFROM td3_performance\r\nWHERE timestamp BETWEEN '${__from:date}' AND '${__to:date}'\r\nand shard in ($Shard)\r\nSAMPLE BY $__sampleByInterval \r\nALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Time taken",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  avg(timeTakenMs) AS \" \",\r\n  shard AS \"metric\"\r\nFROM td3_performance\r\nWHERE timestamp BETWEEN '${__from:date}' AND '${__to:date}'\r\nand shard in ($Shard)\r\nSAMPLE BY $__sampleByInterval \r\nALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Result codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  shard,\r\n  avg(resultCodes_200) as \"200\",\r\n  avg(resultCodes_403) as \"403\",\r\n  avg(resultCodes_404) as \"404\"\r\nFROM td3_performance\r\nWHERE timestamp BETWEEN '${__from:date}' AND '${__to:date}'\r\nand shard in ($Shard)\r\nSAMPLE BY $__sampleByInterval \r\nALIGN TO CALENDAR\r\n",
     "selectedFormat": 2
    }
   ]
  }
 ]
}